"""Pure, QGIS-free contracts for one human-approved pending agent action.

Phase 04 turns an accepted inert proposal (``model_patch`` / ``layer_style``)
into a *pending action* that still mutates nothing until the human clicks Apply.
This module owns only the standard-library pieces:

- :func:`proposal_digest` -- a deterministic integrity tag over the proposal's
  already-bounded, privacy-preserving public ``to_dict()`` tree (no secret, no
  feature/category values);
- :class:`ApprovalState` -- a single-use approval nonce bound to one action id,
  compared in constant time, that the provider can never forge or supply;
- :class:`PendingAction` -- the frozen, copy-safe record the dock keeps for the
  one pending action, exposing only a bounded public card to the UI.

Nothing here touches a live QgsProject/layer/graph, applies anything, resolves a
context token, or serializes the retained parsed proposal to the provider.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import secrets
import uuid
from dataclasses import dataclass
from typing import Any, Optional

from . import context as agent_context

# The one pending action expires after this many seconds even if the live state
# is otherwise unchanged, so a forgotten card cannot be applied much later. The
# context token is still the primary freshness guard; this is defense in depth.
DEFAULT_TTL_SECONDS = 300.0

_MAX_CARD_TITLE = 160
_MAX_CARD_TARGET = 200
_MAX_CARD_SUMMARY = 2_000


def proposal_digest(proposal: Any) -> str:
    """Return a deterministic SHA-256 hex digest of ``proposal.to_dict()``.

    The digest is computed only by trusted code and binds a pending action to
    the exact proposal the human reviewed. It embeds no secret and, because it
    is taken over the bounded public proposal tree, carries no feature/category
    value. A mismatch at the click boundary rejects the apply.
    """
    tree = proposal.to_dict()
    canonical = json.dumps(
        tree, ensure_ascii=False, sort_keys=True, allow_nan=False, separators=(",", ":")
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


class ApprovalState:
    """A single-use approval nonce bound to exactly one pending action id.

    The nonce is generated by trusted application code with
    ``secrets.token_hex``; a provider can neither read nor supply it. ``consume``
    succeeds at most once and only for the exact ``(action_id, nonce)`` pair,
    using a constant-time comparison; every later, foreign, or absent attempt
    fails closed. This makes a double-click / late signal apply at most once.
    """

    def __init__(self, action_id: str, nonce: Optional[str] = None) -> None:
        if not isinstance(action_id, str) or not action_id:
            raise ValueError("An approval state requires a non-empty action id.")
        self._action_id = action_id
        self._nonce = nonce if isinstance(nonce, str) and nonce else secrets.token_hex(16)
        self._used = False

    @property
    def action_id(self) -> str:
        return self._action_id

    @property
    def nonce(self) -> str:
        return self._nonce

    @property
    def used(self) -> bool:
        return self._used

    def consume(self, action_id: Any, nonce: Any) -> bool:
        """Return ``True`` exactly once, for the exact matching id and nonce."""
        if self._used:
            return False
        if not isinstance(action_id, str) or not isinstance(nonce, str):
            return False
        # Constant-time compares so neither value can be learned byte by byte.
        id_ok = hmac.compare_digest(action_id, self._action_id)
        nonce_ok = hmac.compare_digest(nonce, self._nonce)
        if id_ok and nonce_ok:
            self._used = True
            return True
        return False


@dataclass(frozen=True)
class PendingAction:
    """The one pending, human-approvable action. Frozen and copy-safe.

    ``proposal`` is the detached parsed proposal object retained internally for
    re-validation and apply; it is never serialized to the provider or into
    session memory. Only :meth:`to_public_card` leaves this object toward the UI.
    """

    action_id: str
    kind: str
    proposal: Any
    preview: dict
    digest: str
    target_identity: str
    context_token: str
    mode: str
    scope: str
    created_at: float
    expires_at: float
    approval: ApprovalState

    @property
    def is_destructive(self) -> bool:
        return bool(self.preview.get("destructive", False))

    def is_expired(self, now: float) -> bool:
        return now >= self.expires_at

    def to_public_card(self) -> dict:
        """Return a bounded, detached dict for the approval card.

        Contains no parsed-proposal object, no context-token secret, no digest,
        and no value beyond what the accepted Phase 03 preview already exposes.
        """
        preview = self.preview if isinstance(self.preview, dict) else {}
        card = {
            "action_id": self.action_id,
            "kind": self.kind,
            "title": agent_context.bound_text(preview.get("title", ""), _MAX_CARD_TITLE),
            "target": agent_context.bound_text(preview.get("target", ""), _MAX_CARD_TARGET),
            "summary": agent_context.bound_text(preview.get("summary", ""), _MAX_CARD_SUMMARY),
            "destructive": self.is_destructive,
            "warnings": [
                agent_context.bound_text(w, 500)
                for w in (preview.get("warnings", []) or [])[:20]
                if isinstance(w, str)
            ],
            "applied": False,
        }
        # Carry the same bounded human-readable impact lines the preview holds.
        for line_key in ("operations", "changes", "validation_issues"):
            value = preview.get(line_key)
            if isinstance(value, list):
                card[line_key] = value[:60]
        for flag in ("operation_count", "incomplete", "validation_issues_truncated"):
            if flag in preview:
                card[flag] = preview[flag]
        return card


def build_pending_action(
    kind: str,
    proposal: Any,
    preview: dict,
    target_identity: str,
    context_token: str,
    mode: str,
    scope: str,
    *,
    now: float,
    ttl_seconds: float = DEFAULT_TTL_SECONDS,
    action_id: Optional[str] = None,
) -> PendingAction:
    """Construct the single :class:`PendingAction` for a validated Act proposal.

    The caller (the trusted dock) is responsible for enforcing the one-pending
    rule; this only builds the immutable record plus its fresh approval nonce.
    """
    aid = action_id or uuid.uuid4().hex
    return PendingAction(
        action_id=aid,
        kind=kind,
        proposal=proposal,
        preview=dict(preview) if isinstance(preview, dict) else {},
        digest=proposal_digest(proposal),
        target_identity=target_identity,
        context_token=context_token,
        mode=mode,
        scope=scope,
        created_at=now,
        expires_at=now + max(1.0, float(ttl_seconds)),
        approval=ApprovalState(aid),
    )
